travis:
  secure:
    BINSTAR_TOKEN: Ay3m/mMiWcVbhkqDGiZIMlY58ZDMTN+Wkvs+NvC4rASJu5mEtoNjQxYly1B7vkZnOup+FSycW0NVXFZNI807AN/cwKoNXYtyGNdy1Q4wzwohXYmSKYykjyMOK+pGwbQ5Se26ZMzMERq2oza91RohZ6N81c8FJE+p6QXepZkpYlGiP12igsW3wvxzTFqfwaXe0gU/a39G1grbJ28PuyWcoqNAUDOGvMeV4F6TFpOM7QpNPuEOKaxW1+rDp2IWGmi9JxPeko8fhX/mDGmXKpqcthWdmSdmNQtctGoQYbdO7cLIB2X9Eiz/1UqSohupQ9o+BXW2vCJgdU7pytA00f2poWRQKj3Bf4Fdu20Y2FYwQG7rMdpPo4v9InRDQvEO9K7JIZE9OwbItj/jC2QAB1bzhwjufR/c2PyKzM3srZC38ThcCN/PY6ceCq/UEov4bnf1KMdBK3INYCyO6LVmVDQpxF/QmhjL9HyiUfxv8UeAxTRuFhSGXJrQCOKE3BEt4/BFWHaU9Oy0N/IcV/vNpl160hPood/gg+fMTzmekZ1WZEfOAXoynmdnJFOMP05rvU1MEubBSFg6gfdjdOac8tEbRumGPwlH6CbgIag/ZeC9mOz5mjI3b0dpEHzEUbpP72kuHPtznKdQmDdJ7R8NVM8i15vAPdjtkx+yI0LIvQ6Ab1g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
